# Generated by Django 4.2.1 on 2023-07-01 23:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseinfo_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='课程详情'),
        ),
    ]
