# Generated by Django 4.2.1 on 2023-07-01 23:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfo',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='机构详情'),
        ),
    ]
